services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: book-review-system
    restart: unless-stopped
    ports:
      - "${PORT:-4000}:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - MONGO_URI=mongodb://mongo:27017/book_review_system
      - JWT_SECRET=${JWT_SECRET:-supersecret_jwt_key}
      - JWT_EXPIRES_IN=7d
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6380:6379"

volumes:
  mongo_data:
